apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timer-server
  template:
    metadata:
      labels:
        app: timer-server
    spec:
      containers:
      - name: timer-server
        image: mbravov/timer-server:latest
        ports:
        - containerPort: 5000
