apiVersion: v1
kind: Service
metadata:
  name: timer-server-service
spec:
  type: NodePort
  selector:
    app: timer-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30008
